---
title: "CEM+MRT"
subtitle: "Execution"
author: "Ryo Mishima"
date: "`r Sys.Date()`"
output: html_document
---

# Setup
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Display R version information
R.version.string
```

```{r}
# Clear workspace
rm(list = ls(all.names = TRUE))
```

```{r}
f_doParallel <- function(cores = NA) {
  require(foreach)
  require(doParallel)
  
  # Determine number of cores to use
  if (is.na(cores)) {
    cores <- detectCores()
  } else if (cores < 1) {
    cores <- floor(detectCores() * cores)
  } else {
    cores <- cores
  }
  
  # aviod "all connections are in use"
  # closeAllConnections()
  
  # Create and register cluster
  cluster <- makeCluster(cores - 1)
  registerDoParallel(cluster)
  
  return(cluster)
}
```

# Data Generation
```{r, include=FALSE}
# Generate simulation data
rmarkdown::render(input = "./sim_data.Rmd")
SimDatas <- f_GEN_DATA(n_sim, n_total, corr, n_Xobs, p_dichot, n_Xunk, beta, alpha)
```

```{r}
# output simulation data as csv
write.csv(SimDatas, "sim_data.csv", row.names=FALSE, fileEncoding="shift-jis")
```

# Inference
```{r, include=FALSE}
rmarkdown::render(input = "../../sim_inference.Rmd")
```

# Analysis Methods
```{r, include=FALSE}
# Render analysis scripts
rmarkdown::render(input = "../../sim_01_PSM_.Rmd", output_dir = "./")
```

```{r, include=FALSE}
rmarkdown::render(input = "../../sim_02_CEM_.Rmd", output_dir = "./")
```

```{r, include=FALSE}
rmarkdown::render(input = "../../sim_03_CART_.Rmd", output_dir = "./")
```

```{r, include=FALSE}
rmarkdown::render(input = "../../sim_04_RF_.Rmd", output_dir = "./")
```

```{r, include=FALSE}
rmarkdown::render(input = "../../sim_05_MRT_.Rmd", output_dir = "./")
```

```{r, include=FALSE}
# rmarkdown::render(input = "../../sim_06_SIRUS_.Rmd", output_dir = "./")
```

# Completion Notification
```{r, include=FALSE}
# Play sound when execution completes
require(beepr)
beep(sound = 5, expr = NULL)
```
